=== yanalexanderadames-gif/Tasca_Avaluable_4_1/cataleg.dtd
<!ELEMENT cataleg (single | album)+>

<!ELEMENT single (titol, descripcio?, pais, idioma, genere*, grup, membres, durada)>
<!ATTLIST single codi CDATA #REQUIRED>

<!ELEMENT album (titol, descripcio?, pais, idioma, genere*, grup, membres, numero_cançons, titols_cançons)>
<!ATTLIST album codi CDATA #REQUIRED>

<!ELEMENT titol (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>

<!ELEMENT genere (Música_clásica |Jazz |Blues |Góspel |Soul |Pop |Rock_and_Roll |Country)>
<!ELEMENT Música_clásica EMPTY>
<!ELEMENT Jazz EMPTY>
<!ELEMENT Blues EMPTY>
<!ELEMENT Góspel EMPTY>
<!ELEMENT Soul EMPTY>
<!ELEMENT Pop EMPTY>
<!ELEMENT Rock_and_Roll EMPTY>
<!ELEMENT Country EMPTY>


<!ELEMENT grup (#PCDATA)>
<!ELEMENT membres (membre+)>
<!ELEMENT membre (nom)>
<!ATTLIST membre sexe (home | dona) #REQUIRED>
<!ELEMENT nom (#PCDATA)>

<!ELEMENT dur (#PCDATA)> <!ELEMENT durada (#PCDATA)>

<!ELEMENT numero_cançons (#PCDATA)>
<!ELEMENT titols_cançons (canço+)>
<!ELEMENT canço (titol_canço, durada_canço)>
<!ATTLIST canço numero CDATA #REQUIRED>

<!ELEMENT titol_canço (#PCDATA)>
<!ELEMENT durada_canço (#PCDATA)>

=== yanalexanderadames-gif/Tasca_Avaluable_4_1/Tasca Avaluable 4.1/cataleg.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cataleg SYSTEM "cataleg.dtd">

<cataleg>
    <single codi="S001">
        <titol>Flowers</titol>
        <descripcio>Single de gran èxit mundial</descripcio>
        <pais>USA</pais>
        <idioma>Anglès</idioma>
        <genere><Pop/></genere>
        <grup>Miley Cyrus</grup>
        <membres>
            <membre sexe="dona">
                <nom>Miley Cyrus</nom>
            </membre>
        </membres>
        <durada>3:20</durada>
    </single>

    <album codi="A001">
        <titol>Kind of Blue</titol>
        <pais>USA</pais>
        <idioma>Instrumental</idioma>
        <genere><Jazz/></genere>
        <grup>Miles Davis Sextet</grup>
        <membres>
            <membre sexe="home">
                <nom>Miles Davis</nom>
            </membre>
            <membre sexe="home">
                <nom>John Coltrane</nom>
            </membre>
        </membres>
        <numero_cançons>2</numero_cançons>
        <titols_cançons>
            <canço numero="1">
                <titol_canço>So What</titol_canço>
                <durada_canço>9:22</durada_canço>
            </canço>
            <canço numero="2">
                <titol_canço>Freddie Freeloader</titol_canço>
                <durada_canço>9:46</durada_canço>
            </canço>
        </titols_cançons>
    </album>
</cataleg>
